## Упражнения по библиотеке Numpy

In [ ]:
import numpy as np

**1.** Дан случайный массив, поменять знак у элементов, значения которых между 3 и 8

In [ ]:
arr = np.arange(10)
print(arr)

arr[(arr>3) & (arr<8)] *= -1
arr

[0 1 2 3 4 5 6 7 8 9]


array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9])

**2.** Заменить максимальный элемент случайного массива на 0

In [ ]:
arr[np.argmax(arr)] = 0
arr

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  0])

**3.** Построить прямое произведение массивов (все комбинации с каждым элементом). На вход подается двумерный массив

In [ ]:
arrays = ([[1,2,3],[4,5],[6]])
res = np.array(np.meshgrid(*arrays))
mesh.T.reshape(-1, len(arrays))

array([[1, 4, 7],
       [1, 5, 7],
       [2, 4, 7],
       [2, 5, 7],
       [3, 4, 7],
       [3, 5, 7],
       [1, 4, 8],
       [1, 5, 8],
       [2, 4, 8],
       [2, 5, 8],
       [3, 4, 8],
       [3, 5, 8],
       [1, 4, 9],
       [1, 5, 9],
       [2, 4, 9],
       [2, 5, 9],
       [3, 4, 9],
       [3, 5, 9]])

**4.** Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [ ]:
A = np.array([[0,1,2], [2,0,5], [6,7,8], [9,10,11], [2,1,5], [15,16,17], [18,19,20], [21,22,23]])
B = np.array([[0,1],[2,5]])
print(A)
print(B)
A[np.isin(A,B).all(axis=1)]

[[ 0  1  2]
 [ 2  0  5]
 [ 6  7  8]
 [ 9 10 11]
 [ 2  1  5]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
[[0 1]
 [2 5]]


array([[0, 1, 2],
       [2, 0, 5],
       [2, 1, 5]])

**5.** Дана 10x3 матрица, найти строки из неравных значений (например строка [2,2,3] остается, строка [3,3,3] удаляется)

In [ ]:
a = np.array([[1,2,3], [4,4,4], [4,5,4]])
a[np.any(a != a[:, [0]], axis=1)]

array([[1, 2, 3],
       [4, 5, 4]])

**6.** Дан двумерный массив. Удалить те строки, которые повторяются

In [ ]:
a = np.array([[1,2],[3,4],[1,2],[7,8]])
print(a)
a = np.unique(a,axis=0)
print(a)

[[1 2]
 [3 4]
 [1 2]
 [7 8]]
[[1 2]
 [3 4]
 [7 8]]


______
______

Для каждой из следующих задач (1-5) нужно привести 2 реализации – одна без использования numpy (cчитайте, что там, где на входе или выходе должны быть numpy array, будут просто списки), а вторая полностью векторизованная с использованием numpy (без использования питоновских циклов/map/list comprehension).


__Замечание 1.__ Можно считать, что все указанные объекты непустые (к примеру, в __задаче 1__ на диагонали матрицы есть ненулевые элементы).

__Замечание 2.__ Для большинства задач решение занимает не больше 1-2 строк.

___

* __Задача 1__: Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы.  
 Например, для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

In [ ]:
def mat_prod(matrix):
  prod = 1
  for i in range(min(len(matrix), len(matrix[0]))):
    if matrix[i][i] != 0:
      prod *= matrix[i][i]
  return prod

X = [[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]
print(mat_prod(X))

3


In [ ]:
xn = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]])
a = np.diag(xn)
a[a != 0].prod()

3

* __Задача 2__: Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.  
  Например, для x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) ответ True.

In [ ]:
x1 = [1, 2, 2, 4]
y1 = [4, 2, 1, 2]

def multi(x, y):
    if len(x) != len(y):
        return False

    x_sorted = sorted(x)
    y_sorted = sorted(y)

    return x_sorted == y_sorted

result = multi(x1, y1)
print(result)


True


In [ ]:
x1 = np.array([1, 2, 2, 4])
y1 = np.array([4, 2, 1, 2])
(np.unique(x1, return_counts=True)[1] == np.unique(y1, return_counts=True)[1]).all()

True

* __Задача 3__: Найти максимальный элемент в векторе x среди элементов, перед которыми стоит ноль.
 Например, для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.

In [ ]:
n = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
def find_max(x):
    max = None
    for i in range(1, len(x)):
        if x[i-1] == 0 and (max is None or x[i] > max):
            max = x[i]

    return max
find_max(n)

5

In [ ]:
indexs = np.where(n[:len(n)-1]==0)

In [ ]:
indexs = np.array(indexs)

In [ ]:
np.max(n[indexs+1])

5

* __Задача 4__: Реализовать кодирование длин серий (Run-length encoding). Для некоторого вектора x необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить.  
 Например, для x = np.array([2, 2, 2, 3, 3, 3, 5]) ответ (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [ ]:
def run_length(x):
    x = sorted(x)
    values = []
    lengths = []
    current_value = x[0]
    current_length = 1
    for i in range(1, len(x)):
        if x[i] == current_value:
            current_length += 1
        else:
            values.append(current_value)
            lengths.append(current_length)
            current_value = x[i]
            current_length = 1

    values.append(current_value)
    lengths.append(current_length)

    return values, lengths

x = [2, 3, 2, 3, 2, 5, 3]
run_length(x)

([2, 3, 5], [3, 3, 1])

In [ ]:
x = np.array( [2, 3, 2, 3, 2, 5, 3])
np.unique(x, return_counts=True)

(array([2, 3, 5]), array([3, 3, 1]))

* __Задача 5__: Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами. Сравните с функцией scipy.spatial.distance.cdist по скорости работы.

In [ ]:
import time
from scipy.spatial import distance
import math

X = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
Y = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

In [ ]:
def euc(x, y):
    distance = 0
    for xi, yi in zip(x, y):
        distance += (xi - yi) ** 2
    return math.sqrt(distance)


def matrix_euc(X, Y):
    distance_matrix = []
    for x in X:
        row = []
        for y in Y:
            row.append(euc(x, y))
        distance_matrix.append(row)
    return distance_matrix

start = time.time()
display(matrix_euc(X, Y))
end = time.time()
end - start


[[33.67491648096547, 84.10707461325711, 135.6981945347837],
 [28.930952282978865, 78.9746794865291, 130.52585950684255],
 [24.372115213907882, 73.85120175054702, 125.35549449465708]]

0.002947568893432617

In [ ]:
start = time.time()
print(np.sqrt(np.sum((X[:,None] - Y) ** 2, axis=2)))
end = time.time()
end - start

[[ 33.67491648  84.10707461 135.69819453]
 [ 28.93095228  78.97467949 130.52585951]
 [ 24.37211521  73.85120175 125.35549449]]


0.0011897087097167969

In [ ]:
start = time.time()
print(distance.cdist(X, Y),'euclidean')
end = time.time()
end - start

[[ 33.67491648  84.10707461 135.69819453]
 [ 28.93095228  78.97467949 130.52585951]
 [ 24.37211521  73.85120175 125.35549449]] euclidean


0.0007340908050537109

_______
________

* #### __Задача 6__: CrunchieMunchies __*__

Вы работаете в отделе маркетинга пищевой компании MyCrunch, которая разрабатывает новый вид вкусных, полезных злаков под названием **CrunchieMunchies**.

Вы хотите продемонстрировать потребителям, насколько полезны ваши хлопья по сравнению с другими ведущими брендами, поэтому вы собрали данные о питании нескольких разных конкурентов.

Ваша задача - использовать вычисления Numpy для анализа этих данных и доказать, что ваши **СrunchieMunchies** - самый здоровый выбор для потребителей.


In [ ]:
import numpy as np

1. Просмотрите файл cereal.csv. Этот файл содержит количества калорий для различных марок хлопьев. Загрузите данные из файла и сохраните их как calorie_stats.

In [ ]:
calorie_stats = np.loadtxt("/content/sample_data/cereal.csv", delimiter=",")
calorie_stats

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

2. В одной порции CrunchieMunchies содержится 60 калорий. Насколько выше среднее количество калорий у ваших конкурентов?

Сохраните ответ в переменной average_calories и распечатайте переменную в терминале

In [ ]:
average_calories = calorie_stats.mean()
average_calories

106.88311688311688

3. Корректно ли среднее количество калорий отражает распределение набора данных? Давайте отсортируем данные и посмотрим.

Отсортируйте данные и сохраните результат в переменной calorie_stats_sorted. Распечатайте отсортированную информацию

In [ ]:
calorie_stats_sorted = np.sort(calorie_stats)
calorie_stats_sorted

array([ 50.,  50.,  50.,  70.,  70.,  80.,  90.,  90.,  90.,  90.,  90.,
        90.,  90., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100., 110., 110., 110.,
       110., 110., 110., 110., 110., 110., 110., 110., 110., 110., 110.,
       110., 110., 110., 110., 110., 110., 110., 110., 110., 110., 110.,
       110., 110., 110., 110., 120., 120., 120., 120., 120., 120., 120.,
       120., 120., 120., 130., 130., 140., 140., 140., 150., 150., 160.])

4. Похоже, что большинство значений выше среднего. Давайте посмотрим, является ли медиана наиболее корректным показателем набора данных.

Вычислите медиану набора данных и сохраните свой ответ в median_calories. Выведите медиану, чтобы вы могли видеть, как она сравнивается со средним значением.

In [ ]:
median_calories = np.median(calorie_stats_sorted)
median_calories

110.0

5. В то время как медиана показывает, что по крайней мере половина наших значений составляет более 100 калорий, было бы более впечатляюще показать, что значительная часть конкурентов имеет более высокое количество калорий, чем CrunchieMunchies.

Рассчитайте различные процентили и распечатайте их, пока не найдете наименьший процентиль, превышающий 60 калорий. Сохраните это значение в переменной nth_percentile.

In [ ]:
nth_percentile = np.percentile(calorie_stats_sorted, 3.3)
nth_percentile

60.16

6. Хотя процентиль показывает нам, что у большинства конкурентов количество калорий намного выше, это неудобная концепция для использования в маркетинговых материалах.

Вместо этого давайте подсчитаем процент хлопьев, в которых содержится более 60 калорий на порцию. Сохраните свой ответ в переменной more_calories и распечатайте его

In [ ]:
more_calories = len(calorie_stats_sorted[calorie_stats_sorted > 60]) / len(calorie_stats_sorted) * 100
more_calories

96.1038961038961

7. Это действительно высокий процент. Это будет очень полезно, когда мы будем продвигать CrunchieMunchies. Но один вопрос заключается в том, насколько велики различия в наборе данных? Можем ли мы сделать обобщение, что в большинстве злаков содержится около 100 калорий или разброс еще больше?

Рассчитайте величину отклонения, найдя стандартное отклонение, Сохраните свой ответ в calorie_std и распечатайте на терминале. Как мы можем включить эту ценность в наш анализ?

In [ ]:
calorie_std = np.std(calorie_stats_sorted)
calorie_std

19.35718533390827

8. Напишите короткий абзац, в котором кратко изложите свои выводы и то, как, по вашему мнению, эти данные могут быть использованы в интересах Mycrunch при маркетинге CrunchieMunchies.

Такое значения стд показывает, что разнообразие в данных есть, однако даже с учетом этого разброса, очень много злаков имеет калорийность больше 60.

Думаю, что это данные можно использовать в рекламе, тк они отображают сущетсвенную разницу с конкуртентами.